services:
  cli:
    build: .
    container_name: cli
    volumes:
      - .:/app
    command: [ "sleep", "infinity" ]

  celery_worker:
    build: .
    container_name: celery_worker
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: [ "celery", "-A", "server.employee_management.scheduler.celery.celery_config", "worker", "--loglevel=info" ]

  celery_beat:
    build: .
    container_name: celery_beat
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: [ "celery", "-A", "server.employee_management.scheduler.celery.celery_config", "beat", "--loglevel=info" ]

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
